### ISSUE TITLE
Featured Image for How to Rank on First Page of Google post

### ISSUE THREAD

**Issue by nikhilpyreddy** [theflair/theflair#1]
The featured image is not linking to the post. The image is present in assets/images/google folder of the repo. Solve it asap.

**Comment by puneethkanna** [comment]
Could you eloborate the issue, where it is occuring.

**Comment by nikhilpyreddy** [comment]
I think I had complicated the explanation of the issue. Just to simple, a image is set in the post, and it's even uploaded to the specified folder. But the image isn't displayed.

**Comment by theflair** [comment]
Fixed.
